### ISSUE TITLE
Wrong completion entry for 'multi_compile'

### ISSUE THREAD

**Issue by ranqn** [amloveyweb/shaderlabvscode#1]
Auto completion entry for `multi_compile` is currently `multi_complie`
<img width="243" alt="image" src="https://user-images.githubusercontent.com/1959571/163664789-b249ac80-6d2a-4469-9352-3bc33af044c5.png">

**Comment by amlovey** [comment]
will fix it in next release. Thank you for feedback!

**Comment by amlovey** [comment]
Fixed in version 1.4.3
